language: csharp
script:
  - xbuild /p:Configuration=Release DefibNet.sln
before_install:
  - sudo apt-get install nunit-console
before_script:
  - nuget restore DefibNet.sln
after_script:
  - nunit-console DefibNetTests/bin/Release/DefibNetTests.dll